In [5]:
import pandas as pd
data={
    "name":["balaraju","dusari","durga","prasad"],
    "marks":[10,20,30,None]
}
df=pd.DataFrame(data)
df

       name  marks
0  balaraju   10.0
1    dusari   20.0
2     durga   30.0
3    prasad    NaN

In [9]:
df.isnull()

    name  marks
0  False  False
1  False  False
2  False  False
3  False   True

In [13]:
df.isnull().sum()

name     0
marks    1
dtype: int64

In [14]:
df.fillna(0)

       name  marks
0  balaraju   10.0
1    dusari   20.0
2     durga   30.0
3    prasad    0.0

In [30]:
df["marks"].fillna(df["marks"].mean())

0    10.0
1    20.0
2    30.0
3    20.0
Name: marks, dtype: float64

In [35]:
df.dropna()# is used to remove the missing valude

       name  marks
0  balaraju   10.0
1    dusari   20.0
2     durga   30.0