In [19]:
import pandas as pd
df=pd.read_csv(r"c:\Users\Admin\Downloads\marksheet.csv")
print(df.to_string())

      id          Name  Gender  Age Section  Science  English  History  Maths
0      1       Bronnie  Female   13       C       21       81       62     49
1      2        Lemmie    Male   15       B       29       41       17     40
2      3         Danya  Female   14       C       12       87       16     96
3      4         Denna  Female   14       B       15       53       82     33
4      5       Jocelin    Male   14       A       43        6        3     21
5      6       Malissa  Female   14       C       98       51       85     76
6      7       Ichabod  Female   14       B       38       74       54     60
7      8      Beverlie    Male   14       B       25       51       41     80
8      9       Corrine    Male   15       A       39       16       22     49
9     10          Tate    Male   15       C       35       25       37     27
10    11          Dunn    Male   15       C      100       93       87     81
11    12       Valaria    Male   13       B       19        5       78     76
12    13       Merrick    Male   15       A       65       89       96     34
13    14        Gracie  Female   13       B       93       38       39     93
14    15         Missy  Female   13       B       98       18       84     74
15    16      Gilberta    Male   15       A       53       30       90     64
16    17         Peggy    Male   13       A       91       45       44     45
17    18          Dory  Female   13       B        5       89       25     23
18    19       Opalina  Female   13       B       62       77       75     72
19    20        Ashlan    Male   13       B       41        6       17      3
20    21         Amery    Male   13       A       76       96       67     17
21    22       Benoite    Male   14       B        3       55       14     90
22    23         Merle  Female   13       C        5       83       19     39
23    24         Valma  Female   14       C       48       83       79     95
24    25          Jone    Male   14       A       17       87       16     50
25    26           Rae  Female   15       A       16       59       18     64
26    27      Charmine  Female   14       A       93       93       83     40
27    28         Hanan    Male   14       A       60       36       86     87
28    29        Adrian    Male   13       C       19        8       76     75
29    30         Livia    Male   13       C       95       65       25     91
30    31        Richie  Female   15       B       14       83        9     90
31    32     Ekaterina  Female   15       B       17       36       45     27
32    33         Tamra  Female   14       C       17       74       11     49
33    34         Zarla  Female   15       B       54       18       46     17
34    35         Tommy  Female   13       B        5       75       13     61
35    36    Anna-diane  Female   15       C       93       53       10     29
36    37          Josh  Female   14       A       54       23       19     94
37    38      Claudina    Male   14       C       90       62       45     21
38    39          Adah  Female   13       A       71       90       78     35
39    40        Luelle    Male   13       B      100       52       89     76
40    41      Johannes  Female   15       C       10       78       56     41
41    42         Hetty  Female   13       B       21       89       72     84
42    43       Brandie    Male   15       B       43        2       17     78
43    44         Arvie  Female   15       B       26       46       81     63
44    45       Jacenta    Male   15       C       65        7       57     27
45    46         Teddy    Male   14       A       50       22       50     78
46    47       Everett  Female   14       A       84       57       25     57
47    48          Lyda  Female   15       C       78       58        1     33
48    49         Vinny    Male   13       B       81       25       99     13
49    50        Karrie    Male   14       A       94       15       66     34
50    51         Skipp    Male   14       C       31       37       77     79
51    52        Rollie  Female   13       A       17       99       29     85
52    53         Ruben  Female   15       B       15       84       40     40
53    54        Tabbie    Male   15       C       23       44       76     46
54    55          Lief    Male   15       B       55       64       56     69
55    56        Olenka  Female   14       B       53       53       49     43
56    57         Hinze    Male   15       A       46       37       63     17
57    58         Issie    Male   14       A       64        1       74      6
58    59       Yardley  Female   14       C       41       37       26     65
59    60       Winslow  Female   14       B       61       71       77     64
60    61        Bobbee  Female   14       C       16       57       90     14
61    62         Fanny  Female   13       C       49       90       13     98
62    63  Massimiliano    Male   14       A       16       45       44      5
63    64       Shannon    Male   15       B       78       74       31     85
64    65          Mufi  Female   14       C       88       72       31     27
65    66      Christan  Female   14       C       85        6       10     85
66    67         Orrin  Female   15       C       45       41       26     12
67    68         Drusi    Male   15       C       39        7      100     70
68    69           Nil  Female   15       A       84       97       70     96
69    70     Jessamine  Female   14       B       34       71       35     47
70    71           Bil  Female   15       C       95       32       91     48
71    72        Jaymie    Male   14       C       48       59       60     58
72    73        Lorrie    Male   13       A       72       78       40     78
73    74       Bethena    Male   13       B       46       89       83     64
74    75        Sascha  Female   13       B       85       10       62     62
75    76        Cherie    Male   15       C       32       31       89     30
76    77         David  Female   13       B       27        2       63    100
77    78          Jody    Male   15       B       87       45       73     48
78    79      Rosalynd    Male   13       C       27       96       89     49
79    80         Elton    Male   13       B       13       18       80     82
80    81      Teresita    Male   15       A        1       90       42     94
81    82        Dannel    Male   15       C       84       85       14     24
82    83        Amabel    Male   14       A       59       12       45     64
83    84        Eugine    Male   13       C       34       18       39     94
84    85         Brien  Female   13       C       36       95       55     46
85    86         Agace    Male   15       C       17       75        8     71
86    87        Aubrey  Female   13       A        8       72       78     14
87    88       Sheffie  Female   15       C       44       55       51    100
88    89         Ranee  Female   15       A       58       16       64     67
89    90         Cobby    Male   15       C       64       20       86     84
90    91          Linn    Male   13       C       23        2       42     43
91    92         Daffi  Female   15       A       79       82       99     81
92    93      Morganne  Female   15       A       22       86        9     38
93    94          Dael  Female   13       A       43       65       18     26
94    95          Ario    Male   14       A       64       18       73     37
95    96       Georgia  Female   15       A       58       10       99     44
96    97      Adolphus    Male   13       A       19       98       13     86
97    98        Silvia    Male   14       A       40       61       63     80
98    99       Brendin    Male   14       C       72       51       50     11
99   100        Loella  Female   15       A       66       20       76     30
100  101    Hildegaard    Male   14       A       64       68       89     43
101  102         Alvin  Female   13       B       80       28       53     67
102  103     Christoph  Female   13       C        2       19       48     52
103  104        Woodie    Male   15       A       37       57       48     75
104  105       Jeannie    Male   13       B       68       97       31     48
105  106      Jocelyne  Female   14       C       62        4       75     32
106  107          Rina  Female   14       C       57       68       13     74
107  108        Virgie  Female   14       B       56       75        5     40
108  109        Vaughn    Male   14       C       11       30       83     17
109  110        Cherry  Female   14       B       82       54       31     18
110  111          Abel    Male   13       A        2       39       13     69
111  112          Matt  Female   15       A       23       65       72     51
112  113        Josefa    Male   13       C       22       78       77     26
113  114       Coretta    Male   14       A       41       52       29     21
114  115         Chris  Female   13       C       23       13       28     69
115  116        Shanie    Male   14       A       80       92       53     30
116  117          Kath    Male   14       A       63       74       46     76
117  118          Bent  Female   14       B       90       22        2     12
118  119        Aretha  Female   13       C        2       60       67     29
119  120         Alyse    Male   14       A       80       34       85     71
120  121      Patrizia    Male   13       A       79       88       96     93
121  122        Gloria    Male   14       C        4       37       50     47
122  123      Brandise    Male   13       A       18      100       39      8
123  124          Orin  Female   15       B       70       75       21     99
124  125       Fredric    Male   14       B       68       20       21     81
125  126           Pat    Male   15       A       29        6       43     85
126  127        Bennie    Male   14       B       76       36       32     47
127  128       Starlin  Female   14       C        3       31       34     45
128  129          Susy  Female   15       B       28       94       61     72
129  130       Eadmund  Female   13       A       23       88       90     68
130  131        Blisse  Female   15       B       85       30       50      2
131  132       Tymothy    Male   13       C       13       73       76     95
132  133       Lindsay    Male   15       A       19       14       43     68
133  134       Jehanna  Female   15       C       77       25       85     26
134  135       Humfrid  Female   13       B       96      100       42     62
135  136        Hector  Female   13       C        5       10       75     38
136  137        Ailene  Female   15       C       52       39       37      3
137  138        Berget    Male   13       C       10       29       21     13
138  139         Bevan    Male   13       B       52       62       44     10
139  140         Ricky  Female   13       B       21       65       90      4
140  141       Isidora    Male   15       C       52       30       14     24
141  142      Emmanuel  Female   14       B       77       79       92     36
142  143      Cristian    Male   13       B        5        3       97     84
143  144         Guido  Female   13       C       63       12       69     41
144  145          Alis    Male   15       A       76       53       32     69
145  146         Brien  Female   15       B       43        4       40     93
146  147    Jaquenette    Male   15       C       33       75       98     84
147  148         Danni  Female   13       B       92       67       13     25
148  149      Adrianne  Female   15       C       51       67       67     91
149  150         Inger  Female   13       B       53       95       75     81
150  151        Herold    Male   13       A       92       97       62     69
151  152       Candide  Female   15       A       26       76       56     75
152  153          Susi    Male   13       A       23       41       49     79
153  154          Milo  Female   14       A       47       16       55     21
154  155         Emlyn    Male   14       C       32        3       69     96
155  156         Sarah  Female   13       B       55       99        8     72
156  157         Paten    Male   15       C       67       88       41      8
157  158         Aldin  Female   13       C       72       24       83     62
158  159        Reagan    Male   14       A       73       71       87     30
159  160         Patty    Male   14       B       61       89       70     68
160  161         Barde  Female   15       C       58       25       23     39
161  162          Pepi  Female   13       A      100       64       16     20
162  163          Page    Male   15       B       44       47       43     55
163  164         Alard  Female   13       A       91       12       15     70
164  165       Fidelia  Female   15       C       35       39       61      9
165  166          Hali    Male   13       C       67       21       60     40
166  167        Keeley    Male   15       C       84        8       71     48
167  168          Dory  Female   13       B       23        5       39     42
168  169        Ilaire    Male   14       C       95       56        4    100
169  170        Ermina  Female   15       B       38       17       76     26
170  171          Fran  Female   15       B       34       74       83     81
171  172       Desmund    Male   14       A       86       92        8     62
172  173      Rosamond    Male   15       C       55       62       57     56
173  174       Margaux    Male   14       A       94       28        6      9
174  175        Shalom  Female   14       B       63        9       91     88
175  176          Ivan    Male   14       C       95       21       51     33
176  177        Guntar    Male   13       B       92       36       59     48
177  178       Moselle  Female   15       A       87       39       48     53
178  179           Val    Male   13       B       95       73       91     61
179  180         Amber  Female   15       C       32        5       53     49
180  181       Davidde    Male   13       C       98      100       23     84
181  182       Richard    Male   13       A       62       42       87     51
182  183     Sebastian  Female   15       A       60       42       49     25
183  184        Billie  Female   13       C       53       37       83     64
184  185       Purcell    Male   14       B       75       14       54     68
185  186        Alaine    Male   15       A       48        2       63     91
186  187     Goldarina    Male   14       A       27       11       18     92
187  188       Ruperto  Female   14       B       60       55       30     83
188  189        Oberon  Female   15       C       87       21       41     24
189  190       Ezekiel    Male   13       A       14        6       29     72
190  191         Estel    Male   14       C       38       66       53     32
191  192         Jayme    Male   13       B       39       14       77     53
192  193        Hebert    Male   15       A       50       48       13     15
193  194        Olivia  Female   13       B       48        4       79     76
194  195         Darya    Male   15       C       13       35       71     30
195  196          Nita    Male   14       A       92       57       31     75
196  197     Elbertina  Female   14       A       82        4       56     22
197  198         Carol  Female   14       B       98       13       35      4
198  199          Codi    Male   14       C       30       62       32     60
199  200          Codi  Female   15       A       57       68       56     23
200  201        Ruddie  Female   15       B       84       97       88     64
201  202       Baudoin    Male   14       C       89       59       33     91
202  203         Norri    Male   14       B       45       21       61     13
203  204        Nealon    Male   14       B       84       10       71      8
204  205        Willem  Female   13       C        7       47       39     16
205  206       Rosalyn    Male   15       C       54       89       59     88
206  207        Fannie    Male   14       C       49       48       81     44
207  208         Davis    Male   13       A       56       12       75     96
208  209         Zenia  Female   14       C       59       94       94     47
209  210      Alasteir    Male   13       A        7       29       30     23
210  211        Vivyan    Male   14       A       28       30       80     33
211  212           Reg    Male   15       A       85        8       88     82
212  213     Evangelin    Male   15       C       63       92       38     60
213  214         Tucky  Female   15       A       87       17       94     41
214  215      Betteann    Male   13       C       68       79       71     41
215  216          Elyn    Male   15       A        5       86       48     57
216  217          Kirk  Female   14       A       71       88       44     13
217  218          Zack    Male   13       B       72       46       40     90
218  219         Buffy    Male   14       C       58       60        7     90
219  220         Tammy    Male   13       B       81       63       16     62
220  221        Ericka    Male   14       A        6       53       71     21
221  222         Natty  Female   13       A       60       52       85     39
222  223          Leda  Female   15       B       92       76       72     71
223  224         Tabbi  Female   13       A      100       95       36     10
224  225       Romonda  Female   13       C       84       10       82     93
225  226         Blake  Female   15       B       16        4       49      1
226  227       Josepha  Female   14       C       22       26        1     28
227  228      Maureene  Female   14       B       78       63       62     38
228  229      Ginnifer  Female   14       C        4       15        6     32
229  230          Kent    Male   15       C       15       26       83     75
230  231      Stillman    Male   15       B       50       70       31     98
231  232         Maude    Male   13       A       81       45       22     36
232  233         Alysa    Male   14       B       65       32       67     35
233  234      Mortimer    Male   15       C       91       33       71     81
234  235       Fleming    Male   13       C       31        9       79     54
235  236         Nadia  Female   15       B       98       30       37     56
236  237         Britt    Male   15       C       92       87       38     53
237  238         Lazar  Female   15       A       54       34       66     97
238  239        Ashlin  Female   14       A       49       47       19     55
239  240       Raimund    Male   15       C        2        4       48     46
240  241      Claudell    Male   14       C       76       15       70     35
241  242         Janey    Male   15       C        3       49       67     96
242  243        Morrie  Female   13       B       17       24       41     21
243  244       Domingo    Male   13       C       95       63       65     71
244  245      Jesselyn  Female   15       C       11       53       15     13
245  246        Nickie    Male   13       C       28       15       25     10
246  247           Rog  Female   13       B        1        4       68     65
247  248          Kaia    Male   15       B       93       48       82     44
248  249          Anni  Female   14       B       35       73       66     59
249  250      Fernande    Male   15       B       50        8       80     78

In [ ]:
df.groupby("Gender")["Maths"].count()

Gender
Female    100
Male      100
Name: Maths, dtype: int64

In [14]:
df.groupby("Gender")["Maths"].mean()

Gender
Female    50.364407
Male      55.386364
Name: Maths, dtype: float64

In [15]:
df.groupby("Gender")["Maths"].max()

Gender
Female    100
Male      100
Name: Maths, dtype: int64

In [18]:
df.groupby("Gender")["Maths"].min()

Gender
Female    1
Male      3
Name: Maths, dtype: int64

In [21]:
df.groupby("Section")["Maths"].max()

Section
A     97
B    100
C    100
Name: Maths, dtype: int64

In [23]:
df.groupby("Section")["Maths"].min()

Section
A    5
B    1
C    3
Name: Maths, dtype: int64

In [31]:
female_students=df[df["Gender"]=="Female"]
print(female_students.to_string())

      id        Name  Gender  Age Section  Science  English  History  Maths
0      1     Bronnie  Female   13       C       21       81       62     49
2      3       Danya  Female   14       C       12       87       16     96
3      4       Denna  Female   14       B       15       53       82     33
5      6     Malissa  Female   14       C       98       51       85     76
6      7     Ichabod  Female   14       B       38       74       54     60
13    14      Gracie  Female   13       B       93       38       39     93
14    15       Missy  Female   13       B       98       18       84     74
17    18        Dory  Female   13       B        5       89       25     23
18    19     Opalina  Female   13       B       62       77       75     72
22    23       Merle  Female   13       C        5       83       19     39
23    24       Valma  Female   14       C       48       83       79     95
25    26         Rae  Female   15       A       16       59       18     64
26    27    Charmine  Female   14       A       93       93       83     40
30    31      Richie  Female   15       B       14       83        9     90
31    32   Ekaterina  Female   15       B       17       36       45     27
32    33       Tamra  Female   14       C       17       74       11     49
33    34       Zarla  Female   15       B       54       18       46     17
34    35       Tommy  Female   13       B        5       75       13     61
35    36  Anna-diane  Female   15       C       93       53       10     29
36    37        Josh  Female   14       A       54       23       19     94
38    39        Adah  Female   13       A       71       90       78     35
40    41    Johannes  Female   15       C       10       78       56     41
41    42       Hetty  Female   13       B       21       89       72     84
43    44       Arvie  Female   15       B       26       46       81     63
46    47     Everett  Female   14       A       84       57       25     57
47    48        Lyda  Female   15       C       78       58        1     33
51    52      Rollie  Female   13       A       17       99       29     85
52    53       Ruben  Female   15       B       15       84       40     40
55    56      Olenka  Female   14       B       53       53       49     43
58    59     Yardley  Female   14       C       41       37       26     65
59    60     Winslow  Female   14       B       61       71       77     64
60    61      Bobbee  Female   14       C       16       57       90     14
61    62       Fanny  Female   13       C       49       90       13     98
64    65        Mufi  Female   14       C       88       72       31     27
65    66    Christan  Female   14       C       85        6       10     85
66    67       Orrin  Female   15       C       45       41       26     12
68    69         Nil  Female   15       A       84       97       70     96
69    70   Jessamine  Female   14       B       34       71       35     47
70    71         Bil  Female   15       C       95       32       91     48
74    75      Sascha  Female   13       B       85       10       62     62
76    77       David  Female   13       B       27        2       63    100
84    85       Brien  Female   13       C       36       95       55     46
86    87      Aubrey  Female   13       A        8       72       78     14
87    88     Sheffie  Female   15       C       44       55       51    100
88    89       Ranee  Female   15       A       58       16       64     67
91    92       Daffi  Female   15       A       79       82       99     81
92    93    Morganne  Female   15       A       22       86        9     38
93    94        Dael  Female   13       A       43       65       18     26
95    96     Georgia  Female   15       A       58       10       99     44
99   100      Loella  Female   15       A       66       20       76     30
101  102       Alvin  Female   13       B       80       28       53     67
102  103   Christoph  Female   13       C        2       19       48     52
105  106    Jocelyne  Female   14       C       62        4       75     32
106  107        Rina  Female   14       C       57       68       13     74
107  108      Virgie  Female   14       B       56       75        5     40
109  110      Cherry  Female   14       B       82       54       31     18
111  112        Matt  Female   15       A       23       65       72     51
114  115       Chris  Female   13       C       23       13       28     69
117  118        Bent  Female   14       B       90       22        2     12
118  119      Aretha  Female   13       C        2       60       67     29
123  124        Orin  Female   15       B       70       75       21     99
127  128     Starlin  Female   14       C        3       31       34     45
128  129        Susy  Female   15       B       28       94       61     72
129  130     Eadmund  Female   13       A       23       88       90     68
130  131      Blisse  Female   15       B       85       30       50      2
133  134     Jehanna  Female   15       C       77       25       85     26
134  135     Humfrid  Female   13       B       96      100       42     62
135  136      Hector  Female   13       C        5       10       75     38
136  137      Ailene  Female   15       C       52       39       37      3
139  140       Ricky  Female   13       B       21       65       90      4
141  142    Emmanuel  Female   14       B       77       79       92     36
143  144       Guido  Female   13       C       63       12       69     41
145  146       Brien  Female   15       B       43        4       40     93
147  148       Danni  Female   13       B       92       67       13     25
148  149    Adrianne  Female   15       C       51       67       67     91
149  150       Inger  Female   13       B       53       95       75     81
151  152     Candide  Female   15       A       26       76       56     75
153  154        Milo  Female   14       A       47       16       55     21
155  156       Sarah  Female   13       B       55       99        8     72
157  158       Aldin  Female   13       C       72       24       83     62
160  161       Barde  Female   15       C       58       25       23     39
161  162        Pepi  Female   13       A      100       64       16     20
163  164       Alard  Female   13       A       91       12       15     70
164  165     Fidelia  Female   15       C       35       39       61      9
167  168        Dory  Female   13       B       23        5       39     42
169  170      Ermina  Female   15       B       38       17       76     26
170  171        Fran  Female   15       B       34       74       83     81
174  175      Shalom  Female   14       B       63        9       91     88
177  178     Moselle  Female   15       A       87       39       48     53
179  180       Amber  Female   15       C       32        5       53     49
182  183   Sebastian  Female   15       A       60       42       49     25
183  184      Billie  Female   13       C       53       37       83     64
187  188     Ruperto  Female   14       B       60       55       30     83
188  189      Oberon  Female   15       C       87       21       41     24
193  194      Olivia  Female   13       B       48        4       79     76
196  197   Elbertina  Female   14       A       82        4       56     22
197  198       Carol  Female   14       B       98       13       35      4
199  200        Codi  Female   15       A       57       68       56     23
200  201      Ruddie  Female   15       B       84       97       88     64
204  205      Willem  Female   13       C        7       47       39     16
208  209       Zenia  Female   14       C       59       94       94     47
213  214       Tucky  Female   15       A       87       17       94     41
216  217        Kirk  Female   14       A       71       88       44     13
221  222       Natty  Female   13       A       60       52       85     39
222  223        Leda  Female   15       B       92       76       72     71
223  224       Tabbi  Female   13       A      100       95       36     10
224  225     Romonda  Female   13       C       84       10       82     93
225  226       Blake  Female   15       B       16        4       49      1
226  227     Josepha  Female   14       C       22       26        1     28
227  228    Maureene  Female   14       B       78       63       62     38
228  229    Ginnifer  Female   14       C        4       15        6     32
235  236       Nadia  Female   15       B       98       30       37     56
237  238       Lazar  Female   15       A       54       34       66     97
238  239      Ashlin  Female   14       A       49       47       19     55
242  243      Morrie  Female   13       B       17       24       41     21
244  245    Jesselyn  Female   15       C       11       53       15     13
246  247         Rog  Female   13       B        1        4       68     65
248  249        Anni  Female   14       B       35       73       66     59

In [44]:
male=df[df["Gender"]=="Male"]
print(male.to_string())

      id          Name Gender  Age Section  Science  English  History  Maths
1      2        Lemmie   Male   15       B       29       41       17     40
4      5       Jocelin   Male   14       A       43        6        3     21
7      8      Beverlie   Male   14       B       25       51       41     80
8      9       Corrine   Male   15       A       39       16       22     49
9     10          Tate   Male   15       C       35       25       37     27
10    11          Dunn   Male   15       C      100       93       87     81
11    12       Valaria   Male   13       B       19        5       78     76
12    13       Merrick   Male   15       A       65       89       96     34
15    16      Gilberta   Male   15       A       53       30       90     64
16    17         Peggy   Male   13       A       91       45       44     45
19    20        Ashlan   Male   13       B       41        6       17      3
20    21         Amery   Male   13       A       76       96       67     17
21    22       Benoite   Male   14       B        3       55       14     90
24    25          Jone   Male   14       A       17       87       16     50
27    28         Hanan   Male   14       A       60       36       86     87
28    29        Adrian   Male   13       C       19        8       76     75
29    30         Livia   Male   13       C       95       65       25     91
37    38      Claudina   Male   14       C       90       62       45     21
39    40        Luelle   Male   13       B      100       52       89     76
42    43       Brandie   Male   15       B       43        2       17     78
44    45       Jacenta   Male   15       C       65        7       57     27
45    46         Teddy   Male   14       A       50       22       50     78
48    49         Vinny   Male   13       B       81       25       99     13
49    50        Karrie   Male   14       A       94       15       66     34
50    51         Skipp   Male   14       C       31       37       77     79
53    54        Tabbie   Male   15       C       23       44       76     46
54    55          Lief   Male   15       B       55       64       56     69
56    57         Hinze   Male   15       A       46       37       63     17
57    58         Issie   Male   14       A       64        1       74      6
62    63  Massimiliano   Male   14       A       16       45       44      5
63    64       Shannon   Male   15       B       78       74       31     85
67    68         Drusi   Male   15       C       39        7      100     70
71    72        Jaymie   Male   14       C       48       59       60     58
72    73        Lorrie   Male   13       A       72       78       40     78
73    74       Bethena   Male   13       B       46       89       83     64
75    76        Cherie   Male   15       C       32       31       89     30
77    78          Jody   Male   15       B       87       45       73     48
78    79      Rosalynd   Male   13       C       27       96       89     49
79    80         Elton   Male   13       B       13       18       80     82
80    81      Teresita   Male   15       A        1       90       42     94
81    82        Dannel   Male   15       C       84       85       14     24
82    83        Amabel   Male   14       A       59       12       45     64
83    84        Eugine   Male   13       C       34       18       39     94
85    86         Agace   Male   15       C       17       75        8     71
89    90         Cobby   Male   15       C       64       20       86     84
90    91          Linn   Male   13       C       23        2       42     43
94    95          Ario   Male   14       A       64       18       73     37
96    97      Adolphus   Male   13       A       19       98       13     86
97    98        Silvia   Male   14       A       40       61       63     80
98    99       Brendin   Male   14       C       72       51       50     11
100  101    Hildegaard   Male   14       A       64       68       89     43
103  104        Woodie   Male   15       A       37       57       48     75
104  105       Jeannie   Male   13       B       68       97       31     48
108  109        Vaughn   Male   14       C       11       30       83     17
110  111          Abel   Male   13       A        2       39       13     69
112  113        Josefa   Male   13       C       22       78       77     26
113  114       Coretta   Male   14       A       41       52       29     21
115  116        Shanie   Male   14       A       80       92       53     30
116  117          Kath   Male   14       A       63       74       46     76
119  120         Alyse   Male   14       A       80       34       85     71
120  121      Patrizia   Male   13       A       79       88       96     93
121  122        Gloria   Male   14       C        4       37       50     47
122  123      Brandise   Male   13       A       18      100       39      8
124  125       Fredric   Male   14       B       68       20       21     81
125  126           Pat   Male   15       A       29        6       43     85
126  127        Bennie   Male   14       B       76       36       32     47
131  132       Tymothy   Male   13       C       13       73       76     95
132  133       Lindsay   Male   15       A       19       14       43     68
137  138        Berget   Male   13       C       10       29       21     13
138  139         Bevan   Male   13       B       52       62       44     10
140  141       Isidora   Male   15       C       52       30       14     24
142  143      Cristian   Male   13       B        5        3       97     84
144  145          Alis   Male   15       A       76       53       32     69
146  147    Jaquenette   Male   15       C       33       75       98     84
150  151        Herold   Male   13       A       92       97       62     69
152  153          Susi   Male   13       A       23       41       49     79
154  155         Emlyn   Male   14       C       32        3       69     96
156  157         Paten   Male   15       C       67       88       41      8
158  159        Reagan   Male   14       A       73       71       87     30
159  160         Patty   Male   14       B       61       89       70     68
162  163          Page   Male   15       B       44       47       43     55
165  166          Hali   Male   13       C       67       21       60     40
166  167        Keeley   Male   15       C       84        8       71     48
168  169        Ilaire   Male   14       C       95       56        4    100
171  172       Desmund   Male   14       A       86       92        8     62
172  173      Rosamond   Male   15       C       55       62       57     56
173  174       Margaux   Male   14       A       94       28        6      9
175  176          Ivan   Male   14       C       95       21       51     33
176  177        Guntar   Male   13       B       92       36       59     48
178  179           Val   Male   13       B       95       73       91     61
180  181       Davidde   Male   13       C       98      100       23     84
181  182       Richard   Male   13       A       62       42       87     51
184  185       Purcell   Male   14       B       75       14       54     68
185  186        Alaine   Male   15       A       48        2       63     91
186  187     Goldarina   Male   14       A       27       11       18     92
189  190       Ezekiel   Male   13       A       14        6       29     72
190  191         Estel   Male   14       C       38       66       53     32
191  192         Jayme   Male   13       B       39       14       77     53
192  193        Hebert   Male   15       A       50       48       13     15
194  195         Darya   Male   15       C       13       35       71     30
195  196          Nita   Male   14       A       92       57       31     75
198  199          Codi   Male   14       C       30       62       32     60
201  202       Baudoin   Male   14       C       89       59       33     91
202  203         Norri   Male   14       B       45       21       61     13
203  204        Nealon   Male   14       B       84       10       71      8
205  206       Rosalyn   Male   15       C       54       89       59     88
206  207        Fannie   Male   14       C       49       48       81     44
207  208         Davis   Male   13       A       56       12       75     96
209  210      Alasteir   Male   13       A        7       29       30     23
210  211        Vivyan   Male   14       A       28       30       80     33
211  212           Reg   Male   15       A       85        8       88     82
212  213     Evangelin   Male   15       C       63       92       38     60
214  215      Betteann   Male   13       C       68       79       71     41
215  216          Elyn   Male   15       A        5       86       48     57
217  218          Zack   Male   13       B       72       46       40     90
218  219         Buffy   Male   14       C       58       60        7     90
219  220         Tammy   Male   13       B       81       63       16     62
220  221        Ericka   Male   14       A        6       53       71     21
229  230          Kent   Male   15       C       15       26       83     75
230  231      Stillman   Male   15       B       50       70       31     98
231  232         Maude   Male   13       A       81       45       22     36
232  233         Alysa   Male   14       B       65       32       67     35
233  234      Mortimer   Male   15       C       91       33       71     81
234  235       Fleming   Male   13       C       31        9       79     54
236  237         Britt   Male   15       C       92       87       38     53
239  240       Raimund   Male   15       C        2        4       48     46
240  241      Claudell   Male   14       C       76       15       70     35
241  242         Janey   Male   15       C        3       49       67     96
243  244       Domingo   Male   13       C       95       63       65     71
245  246        Nickie   Male   13       C       28       15       25     10
247  248          Kaia   Male   15       B       93       48       82     44
249  250      Fernande   Male   15       B       50        8       80     78

In [46]:
section=df[df["Section"]=="A"]
print(section.to_string())

      id          Name  Gender  Age Section  Science  English  History  Maths
4      5       Jocelin    Male   14       A       43        6        3     21
8      9       Corrine    Male   15       A       39       16       22     49
12    13       Merrick    Male   15       A       65       89       96     34
15    16      Gilberta    Male   15       A       53       30       90     64
16    17         Peggy    Male   13       A       91       45       44     45
20    21         Amery    Male   13       A       76       96       67     17
24    25          Jone    Male   14       A       17       87       16     50
25    26           Rae  Female   15       A       16       59       18     64
26    27      Charmine  Female   14       A       93       93       83     40
27    28         Hanan    Male   14       A       60       36       86     87
36    37          Josh  Female   14       A       54       23       19     94
38    39          Adah  Female   13       A       71       90       78     35
45    46         Teddy    Male   14       A       50       22       50     78
46    47       Everett  Female   14       A       84       57       25     57
49    50        Karrie    Male   14       A       94       15       66     34
51    52        Rollie  Female   13       A       17       99       29     85
56    57         Hinze    Male   15       A       46       37       63     17
57    58         Issie    Male   14       A       64        1       74      6
62    63  Massimiliano    Male   14       A       16       45       44      5
68    69           Nil  Female   15       A       84       97       70     96
72    73        Lorrie    Male   13       A       72       78       40     78
80    81      Teresita    Male   15       A        1       90       42     94
82    83        Amabel    Male   14       A       59       12       45     64
86    87        Aubrey  Female   13       A        8       72       78     14
88    89         Ranee  Female   15       A       58       16       64     67
91    92         Daffi  Female   15       A       79       82       99     81
92    93      Morganne  Female   15       A       22       86        9     38
93    94          Dael  Female   13       A       43       65       18     26
94    95          Ario    Male   14       A       64       18       73     37
95    96       Georgia  Female   15       A       58       10       99     44
96    97      Adolphus    Male   13       A       19       98       13     86
97    98        Silvia    Male   14       A       40       61       63     80
99   100        Loella  Female   15       A       66       20       76     30
100  101    Hildegaard    Male   14       A       64       68       89     43
103  104        Woodie    Male   15       A       37       57       48     75
110  111          Abel    Male   13       A        2       39       13     69
111  112          Matt  Female   15       A       23       65       72     51
113  114       Coretta    Male   14       A       41       52       29     21
115  116        Shanie    Male   14       A       80       92       53     30
116  117          Kath    Male   14       A       63       74       46     76
119  120         Alyse    Male   14       A       80       34       85     71
120  121      Patrizia    Male   13       A       79       88       96     93
122  123      Brandise    Male   13       A       18      100       39      8
125  126           Pat    Male   15       A       29        6       43     85
129  130       Eadmund  Female   13       A       23       88       90     68
132  133       Lindsay    Male   15       A       19       14       43     68
144  145          Alis    Male   15       A       76       53       32     69
150  151        Herold    Male   13       A       92       97       62     69
151  152       Candide  Female   15       A       26       76       56     75
152  153          Susi    Male   13       A       23       41       49     79
153  154          Milo  Female   14       A       47       16       55     21
158  159        Reagan    Male   14       A       73       71       87     30
161  162          Pepi  Female   13       A      100       64       16     20
163  164         Alard  Female   13       A       91       12       15     70
171  172       Desmund    Male   14       A       86       92        8     62
173  174       Margaux    Male   14       A       94       28        6      9
177  178       Moselle  Female   15       A       87       39       48     53
181  182       Richard    Male   13       A       62       42       87     51
182  183     Sebastian  Female   15       A       60       42       49     25
185  186        Alaine    Male   15       A       48        2       63     91
186  187     Goldarina    Male   14       A       27       11       18     92
189  190       Ezekiel    Male   13       A       14        6       29     72
192  193        Hebert    Male   15       A       50       48       13     15
195  196          Nita    Male   14       A       92       57       31     75
196  197     Elbertina  Female   14       A       82        4       56     22
199  200          Codi  Female   15       A       57       68       56     23
207  208         Davis    Male   13       A       56       12       75     96
209  210      Alasteir    Male   13       A        7       29       30     23
210  211        Vivyan    Male   14       A       28       30       80     33
211  212           Reg    Male   15       A       85        8       88     82
213  214         Tucky  Female   15       A       87       17       94     41
215  216          Elyn    Male   15       A        5       86       48     57
216  217          Kirk  Female   14       A       71       88       44     13
220  221        Ericka    Male   14       A        6       53       71     21
221  222         Natty  Female   13       A       60       52       85     39
223  224         Tabbi  Female   13       A      100       95       36     10
231  232         Maude    Male   13       A       81       45       22     36
237  238         Lazar  Female   15       A       54       34       66     97
238  239        Ashlin  Female   14       A       49       47       19     55

In [56]:
print(df[df["Age"]>13].to_string())

      id          Name  Gender  Age Section  Science  English  History  Maths
1      2        Lemmie    Male   15       B       29       41       17     40
2      3         Danya  Female   14       C       12       87       16     96
3      4         Denna  Female   14       B       15       53       82     33
4      5       Jocelin    Male   14       A       43        6        3     21
5      6       Malissa  Female   14       C       98       51       85     76
6      7       Ichabod  Female   14       B       38       74       54     60
7      8      Beverlie    Male   14       B       25       51       41     80
8      9       Corrine    Male   15       A       39       16       22     49
9     10          Tate    Male   15       C       35       25       37     27
10    11          Dunn    Male   15       C      100       93       87     81
12    13       Merrick    Male   15       A       65       89       96     34
15    16      Gilberta    Male   15       A       53       30       90     64
21    22       Benoite    Male   14       B        3       55       14     90
23    24         Valma  Female   14       C       48       83       79     95
24    25          Jone    Male   14       A       17       87       16     50
25    26           Rae  Female   15       A       16       59       18     64
26    27      Charmine  Female   14       A       93       93       83     40
27    28         Hanan    Male   14       A       60       36       86     87
30    31        Richie  Female   15       B       14       83        9     90
31    32     Ekaterina  Female   15       B       17       36       45     27
32    33         Tamra  Female   14       C       17       74       11     49
33    34         Zarla  Female   15       B       54       18       46     17
35    36    Anna-diane  Female   15       C       93       53       10     29
36    37          Josh  Female   14       A       54       23       19     94
37    38      Claudina    Male   14       C       90       62       45     21
40    41      Johannes  Female   15       C       10       78       56     41
42    43       Brandie    Male   15       B       43        2       17     78
43    44         Arvie  Female   15       B       26       46       81     63
44    45       Jacenta    Male   15       C       65        7       57     27
45    46         Teddy    Male   14       A       50       22       50     78
46    47       Everett  Female   14       A       84       57       25     57
47    48          Lyda  Female   15       C       78       58        1     33
49    50        Karrie    Male   14       A       94       15       66     34
50    51         Skipp    Male   14       C       31       37       77     79
52    53         Ruben  Female   15       B       15       84       40     40
53    54        Tabbie    Male   15       C       23       44       76     46
54    55          Lief    Male   15       B       55       64       56     69
55    56        Olenka  Female   14       B       53       53       49     43
56    57         Hinze    Male   15       A       46       37       63     17
57    58         Issie    Male   14       A       64        1       74      6
58    59       Yardley  Female   14       C       41       37       26     65
59    60       Winslow  Female   14       B       61       71       77     64
60    61        Bobbee  Female   14       C       16       57       90     14
62    63  Massimiliano    Male   14       A       16       45       44      5
63    64       Shannon    Male   15       B       78       74       31     85
64    65          Mufi  Female   14       C       88       72       31     27
65    66      Christan  Female   14       C       85        6       10     85
66    67         Orrin  Female   15       C       45       41       26     12
67    68         Drusi    Male   15       C       39        7      100     70
68    69           Nil  Female   15       A       84       97       70     96
69    70     Jessamine  Female   14       B       34       71       35     47
70    71           Bil  Female   15       C       95       32       91     48
71    72        Jaymie    Male   14       C       48       59       60     58
75    76        Cherie    Male   15       C       32       31       89     30
77    78          Jody    Male   15       B       87       45       73     48
80    81      Teresita    Male   15       A        1       90       42     94
81    82        Dannel    Male   15       C       84       85       14     24
82    83        Amabel    Male   14       A       59       12       45     64
85    86         Agace    Male   15       C       17       75        8     71
87    88       Sheffie  Female   15       C       44       55       51    100
88    89         Ranee  Female   15       A       58       16       64     67
89    90         Cobby    Male   15       C       64       20       86     84
91    92         Daffi  Female   15       A       79       82       99     81
92    93      Morganne  Female   15       A       22       86        9     38
94    95          Ario    Male   14       A       64       18       73     37
95    96       Georgia  Female   15       A       58       10       99     44
97    98        Silvia    Male   14       A       40       61       63     80
98    99       Brendin    Male   14       C       72       51       50     11
99   100        Loella  Female   15       A       66       20       76     30
100  101    Hildegaard    Male   14       A       64       68       89     43
103  104        Woodie    Male   15       A       37       57       48     75
105  106      Jocelyne  Female   14       C       62        4       75     32
106  107          Rina  Female   14       C       57       68       13     74
107  108        Virgie  Female   14       B       56       75        5     40
108  109        Vaughn    Male   14       C       11       30       83     17
109  110        Cherry  Female   14       B       82       54       31     18
111  112          Matt  Female   15       A       23       65       72     51
113  114       Coretta    Male   14       A       41       52       29     21
115  116        Shanie    Male   14       A       80       92       53     30
116  117          Kath    Male   14       A       63       74       46     76
117  118          Bent  Female   14       B       90       22        2     12
119  120         Alyse    Male   14       A       80       34       85     71
121  122        Gloria    Male   14       C        4       37       50     47
123  124          Orin  Female   15       B       70       75       21     99
124  125       Fredric    Male   14       B       68       20       21     81
125  126           Pat    Male   15       A       29        6       43     85
126  127        Bennie    Male   14       B       76       36       32     47
127  128       Starlin  Female   14       C        3       31       34     45
128  129          Susy  Female   15       B       28       94       61     72
130  131        Blisse  Female   15       B       85       30       50      2
132  133       Lindsay    Male   15       A       19       14       43     68
133  134       Jehanna  Female   15       C       77       25       85     26
136  137        Ailene  Female   15       C       52       39       37      3
140  141       Isidora    Male   15       C       52       30       14     24
141  142      Emmanuel  Female   14       B       77       79       92     36
144  145          Alis    Male   15       A       76       53       32     69
145  146         Brien  Female   15       B       43        4       40     93
146  147    Jaquenette    Male   15       C       33       75       98     84
148  149      Adrianne  Female   15       C       51       67       67     91
151  152       Candide  Female   15       A       26       76       56     75
153  154          Milo  Female   14       A       47       16       55     21
154  155         Emlyn    Male   14       C       32        3       69     96
156  157         Paten    Male   15       C       67       88       41      8
158  159        Reagan    Male   14       A       73       71       87     30
159  160         Patty    Male   14       B       61       89       70     68
160  161         Barde  Female   15       C       58       25       23     39
162  163          Page    Male   15       B       44       47       43     55
164  165       Fidelia  Female   15       C       35       39       61      9
166  167        Keeley    Male   15       C       84        8       71     48
168  169        Ilaire    Male   14       C       95       56        4    100
169  170        Ermina  Female   15       B       38       17       76     26
170  171          Fran  Female   15       B       34       74       83     81
171  172       Desmund    Male   14       A       86       92        8     62
172  173      Rosamond    Male   15       C       55       62       57     56
173  174       Margaux    Male   14       A       94       28        6      9
174  175        Shalom  Female   14       B       63        9       91     88
175  176          Ivan    Male   14       C       95       21       51     33
177  178       Moselle  Female   15       A       87       39       48     53
179  180         Amber  Female   15       C       32        5       53     49
182  183     Sebastian  Female   15       A       60       42       49     25
184  185       Purcell    Male   14       B       75       14       54     68
185  186        Alaine    Male   15       A       48        2       63     91
186  187     Goldarina    Male   14       A       27       11       18     92
187  188       Ruperto  Female   14       B       60       55       30     83
188  189        Oberon  Female   15       C       87       21       41     24
190  191         Estel    Male   14       C       38       66       53     32
192  193        Hebert    Male   15       A       50       48       13     15
194  195         Darya    Male   15       C       13       35       71     30
195  196          Nita    Male   14       A       92       57       31     75
196  197     Elbertina  Female   14       A       82        4       56     22
197  198         Carol  Female   14       B       98       13       35      4
198  199          Codi    Male   14       C       30       62       32     60
199  200          Codi  Female   15       A       57       68       56     23
200  201        Ruddie  Female   15       B       84       97       88     64
201  202       Baudoin    Male   14       C       89       59       33     91
202  203         Norri    Male   14       B       45       21       61     13
203  204        Nealon    Male   14       B       84       10       71      8
205  206       Rosalyn    Male   15       C       54       89       59     88
206  207        Fannie    Male   14       C       49       48       81     44
208  209         Zenia  Female   14       C       59       94       94     47
210  211        Vivyan    Male   14       A       28       30       80     33
211  212           Reg    Male   15       A       85        8       88     82
212  213     Evangelin    Male   15       C       63       92       38     60
213  214         Tucky  Female   15       A       87       17       94     41
215  216          Elyn    Male   15       A        5       86       48     57
216  217          Kirk  Female   14       A       71       88       44     13
218  219         Buffy    Male   14       C       58       60        7     90
220  221        Ericka    Male   14       A        6       53       71     21
222  223          Leda  Female   15       B       92       76       72     71
225  226         Blake  Female   15       B       16        4       49      1
226  227       Josepha  Female   14       C       22       26        1     28
227  228      Maureene  Female   14       B       78       63       62     38
228  229      Ginnifer  Female   14       C        4       15        6     32
229  230          Kent    Male   15       C       15       26       83     75
230  231      Stillman    Male   15       B       50       70       31     98
232  233         Alysa    Male   14       B       65       32       67     35
233  234      Mortimer    Male   15       C       91       33       71     81
235  236         Nadia  Female   15       B       98       30       37     56
236  237         Britt    Male   15       C       92       87       38     53
237  238         Lazar  Female   15       A       54       34       66     97
238  239        Ashlin  Female   14       A       49       47       19     55
239  240       Raimund    Male   15       C        2        4       48     46
240  241      Claudell    Male   14       C       76       15       70     35
241  242         Janey    Male   15       C        3       49       67     96
244  245      Jesselyn  Female   15       C       11       53       15     13
247  248          Kaia    Male   15       B       93       48       82     44
248  249          Anni  Female   14       B       35       73       66     59
249  250      Fernande    Male   15       B       50        8       80     78

In [57]:
df[df["Maths"]>80]

      id        Name  Gender  Age Section  Science  English  History  Maths
2      3       Danya  Female   14       C       12       87       16     96
10    11        Dunn    Male   15       C      100       93       87     81
13    14      Gracie  Female   13       B       93       38       39     93
21    22     Benoite    Male   14       B        3       55       14     90
23    24       Valma  Female   14       C       48       83       79     95
27    28       Hanan    Male   14       A       60       36       86     87
29    30       Livia    Male   13       C       95       65       25     91
30    31      Richie  Female   15       B       14       83        9     90
36    37        Josh  Female   14       A       54       23       19     94
41    42       Hetty  Female   13       B       21       89       72     84
51    52      Rollie  Female   13       A       17       99       29     85
61    62       Fanny  Female   13       C       49       90       13     98
63    64     Shannon    Male   15       B       78       74       31     85
65    66    Christan  Female   14       C       85        6       10     85
68    69         Nil  Female   15       A       84       97       70     96
76    77       David  Female   13       B       27        2       63    100
79    80       Elton    Male   13       B       13       18       80     82
80    81    Teresita    Male   15       A        1       90       42     94
83    84      Eugine    Male   13       C       34       18       39     94
87    88     Sheffie  Female   15       C       44       55       51    100
89    90       Cobby    Male   15       C       64       20       86     84
91    92       Daffi  Female   15       A       79       82       99     81
96    97    Adolphus    Male   13       A       19       98       13     86
120  121    Patrizia    Male   13       A       79       88       96     93
123  124        Orin  Female   15       B       70       75       21     99
124  125     Fredric    Male   14       B       68       20       21     81
125  126         Pat    Male   15       A       29        6       43     85
131  132     Tymothy    Male   13       C       13       73       76     95
142  143    Cristian    Male   13       B        5        3       97     84
145  146       Brien  Female   15       B       43        4       40     93
146  147  Jaquenette    Male   15       C       33       75       98     84
148  149    Adrianne  Female   15       C       51       67       67     91
149  150       Inger  Female   13       B       53       95       75     81
154  155       Emlyn    Male   14       C       32        3       69     96
168  169      Ilaire    Male   14       C       95       56        4    100
170  171        Fran  Female   15       B       34       74       83     81
174  175      Shalom  Female   14       B       63        9       91     88
180  181     Davidde    Male   13       C       98      100       23     84
185  186      Alaine    Male   15       A       48        2       63     91
186  187   Goldarina    Male   14       A       27       11       18     92
187  188     Ruperto  Female   14       B       60       55       30     83
201  202     Baudoin    Male   14       C       89       59       33     91
205  206     Rosalyn    Male   15       C       54       89       59     88
207  208       Davis    Male   13       A       56       12       75     96
211  212         Reg    Male   15       A       85        8       88     82
217  218        Zack    Male   13       B       72       46       40     90
218  219       Buffy    Male   14       C       58       60        7     90
224  225     Romonda  Female   13       C       84       10       82     93
230  231    Stillman    Male   15       B       50       70       31     98
233  234    Mortimer    Male   15       C       91       33       71     81
237  238       Lazar  Female   15       A       54       34       66     97
241  242       Janey    Male   15       C        3       49       67     96

In [59]:
print(df[df["English"]<40].to_string())

      id       Name  Gender  Age Section  Science  English  History  Maths
4      5    Jocelin    Male   14       A       43        6        3     21
8      9    Corrine    Male   15       A       39       16       22     49
9     10       Tate    Male   15       C       35       25       37     27
11    12    Valaria    Male   13       B       19        5       78     76
13    14     Gracie  Female   13       B       93       38       39     93
14    15      Missy  Female   13       B       98       18       84     74
15    16   Gilberta    Male   15       A       53       30       90     64
19    20     Ashlan    Male   13       B       41        6       17      3
27    28      Hanan    Male   14       A       60       36       86     87
28    29     Adrian    Male   13       C       19        8       76     75
31    32  Ekaterina  Female   15       B       17       36       45     27
33    34      Zarla  Female   15       B       54       18       46     17
36    37       Josh  Female   14       A       54       23       19     94
42    43    Brandie    Male   15       B       43        2       17     78
44    45    Jacenta    Male   15       C       65        7       57     27
45    46      Teddy    Male   14       A       50       22       50     78
48    49      Vinny    Male   13       B       81       25       99     13
49    50     Karrie    Male   14       A       94       15       66     34
50    51      Skipp    Male   14       C       31       37       77     79
56    57      Hinze    Male   15       A       46       37       63     17
57    58      Issie    Male   14       A       64        1       74      6
58    59    Yardley  Female   14       C       41       37       26     65
65    66   Christan  Female   14       C       85        6       10     85
67    68      Drusi    Male   15       C       39        7      100     70
70    71        Bil  Female   15       C       95       32       91     48
74    75     Sascha  Female   13       B       85       10       62     62
75    76     Cherie    Male   15       C       32       31       89     30
76    77      David  Female   13       B       27        2       63    100
79    80      Elton    Male   13       B       13       18       80     82
82    83     Amabel    Male   14       A       59       12       45     64
83    84     Eugine    Male   13       C       34       18       39     94
88    89      Ranee  Female   15       A       58       16       64     67
89    90      Cobby    Male   15       C       64       20       86     84
90    91       Linn    Male   13       C       23        2       42     43
94    95       Ario    Male   14       A       64       18       73     37
95    96    Georgia  Female   15       A       58       10       99     44
99   100     Loella  Female   15       A       66       20       76     30
101  102      Alvin  Female   13       B       80       28       53     67
102  103  Christoph  Female   13       C        2       19       48     52
105  106   Jocelyne  Female   14       C       62        4       75     32
108  109     Vaughn    Male   14       C       11       30       83     17
110  111       Abel    Male   13       A        2       39       13     69
114  115      Chris  Female   13       C       23       13       28     69
117  118       Bent  Female   14       B       90       22        2     12
119  120      Alyse    Male   14       A       80       34       85     71
121  122     Gloria    Male   14       C        4       37       50     47
124  125    Fredric    Male   14       B       68       20       21     81
125  126        Pat    Male   15       A       29        6       43     85
126  127     Bennie    Male   14       B       76       36       32     47
127  128    Starlin  Female   14       C        3       31       34     45
130  131     Blisse  Female   15       B       85       30       50      2
132  133    Lindsay    Male   15       A       19       14       43     68
133  134    Jehanna  Female   15       C       77       25       85     26
135  136     Hector  Female   13       C        5       10       75     38
136  137     Ailene  Female   15       C       52       39       37      3
137  138     Berget    Male   13       C       10       29       21     13
140  141    Isidora    Male   15       C       52       30       14     24
142  143   Cristian    Male   13       B        5        3       97     84
143  144      Guido  Female   13       C       63       12       69     41
145  146      Brien  Female   15       B       43        4       40     93
153  154       Milo  Female   14       A       47       16       55     21
154  155      Emlyn    Male   14       C       32        3       69     96
157  158      Aldin  Female   13       C       72       24       83     62
160  161      Barde  Female   15       C       58       25       23     39
163  164      Alard  Female   13       A       91       12       15     70
164  165    Fidelia  Female   15       C       35       39       61      9
165  166       Hali    Male   13       C       67       21       60     40
166  167     Keeley    Male   15       C       84        8       71     48
167  168       Dory  Female   13       B       23        5       39     42
169  170     Ermina  Female   15       B       38       17       76     26
173  174    Margaux    Male   14       A       94       28        6      9
174  175     Shalom  Female   14       B       63        9       91     88
175  176       Ivan    Male   14       C       95       21       51     33
176  177     Guntar    Male   13       B       92       36       59     48
177  178    Moselle  Female   15       A       87       39       48     53
179  180      Amber  Female   15       C       32        5       53     49
183  184     Billie  Female   13       C       53       37       83     64
184  185    Purcell    Male   14       B       75       14       54     68
185  186     Alaine    Male   15       A       48        2       63     91
186  187  Goldarina    Male   14       A       27       11       18     92
188  189     Oberon  Female   15       C       87       21       41     24
189  190    Ezekiel    Male   13       A       14        6       29     72
191  192      Jayme    Male   13       B       39       14       77     53
193  194     Olivia  Female   13       B       48        4       79     76
194  195      Darya    Male   15       C       13       35       71     30
196  197  Elbertina  Female   14       A       82        4       56     22
197  198      Carol  Female   14       B       98       13       35      4
202  203      Norri    Male   14       B       45       21       61     13
203  204     Nealon    Male   14       B       84       10       71      8
207  208      Davis    Male   13       A       56       12       75     96
209  210   Alasteir    Male   13       A        7       29       30     23
210  211     Vivyan    Male   14       A       28       30       80     33
211  212        Reg    Male   15       A       85        8       88     82
213  214      Tucky  Female   15       A       87       17       94     41
224  225    Romonda  Female   13       C       84       10       82     93
225  226      Blake  Female   15       B       16        4       49      1
226  227    Josepha  Female   14       C       22       26        1     28
228  229   Ginnifer  Female   14       C        4       15        6     32
229  230       Kent    Male   15       C       15       26       83     75
232  233      Alysa    Male   14       B       65       32       67     35
233  234   Mortimer    Male   15       C       91       33       71     81
234  235    Fleming    Male   13       C       31        9       79     54
235  236      Nadia  Female   15       B       98       30       37     56
237  238      Lazar  Female   15       A       54       34       66     97
239  240    Raimund    Male   15       C        2        4       48     46
240  241   Claudell    Male   14       C       76       15       70     35
242  243     Morrie  Female   13       B       17       24       41     21
245  246     Nickie    Male   13       C       28       15       25     10
246  247        Rog  Female   13       B        1        4       68     65
249  250   Fernande    Male   15       B       50        8       80     78

In [65]:
df[(df["Gender"]=="Female") & (df["Section"]=="A") ]

      id       Name  Gender  Age Section  Science  English  History  Maths
25    26        Rae  Female   15       A       16       59       18     64
26    27   Charmine  Female   14       A       93       93       83     40
36    37       Josh  Female   14       A       54       23       19     94
38    39       Adah  Female   13       A       71       90       78     35
46    47    Everett  Female   14       A       84       57       25     57
51    52     Rollie  Female   13       A       17       99       29     85
68    69        Nil  Female   15       A       84       97       70     96
86    87     Aubrey  Female   13       A        8       72       78     14
88    89      Ranee  Female   15       A       58       16       64     67
91    92      Daffi  Female   15       A       79       82       99     81
92    93   Morganne  Female   15       A       22       86        9     38
93    94       Dael  Female   13       A       43       65       18     26
95    96    Georgia  Female   15       A       58       10       99     44
99   100     Loella  Female   15       A       66       20       76     30
111  112       Matt  Female   15       A       23       65       72     51
129  130    Eadmund  Female   13       A       23       88       90     68
151  152    Candide  Female   15       A       26       76       56     75
153  154       Milo  Female   14       A       47       16       55     21
161  162       Pepi  Female   13       A      100       64       16     20
163  164      Alard  Female   13       A       91       12       15     70
177  178    Moselle  Female   15       A       87       39       48     53
182  183  Sebastian  Female   15       A       60       42       49     25
196  197  Elbertina  Female   14       A       82        4       56     22
199  200       Codi  Female   15       A       57       68       56     23
213  214      Tucky  Female   15       A       87       17       94     41
216  217       Kirk  Female   14       A       71       88       44     13
221  222      Natty  Female   13       A       60       52       85     39
223  224      Tabbi  Female   13       A      100       95       36     10
237  238      Lazar  Female   15       A       54       34       66     97
238  239     Ashlin  Female   14       A       49       47       19     55

In [66]:
df[df["Science"]>90]

      id        Name  Gender  Age Section  Science  English  History  Maths
5      6     Malissa  Female   14       C       98       51       85     76
10    11        Dunn    Male   15       C      100       93       87     81
13    14      Gracie  Female   13       B       93       38       39     93
14    15       Missy  Female   13       B       98       18       84     74
16    17       Peggy    Male   13       A       91       45       44     45
26    27    Charmine  Female   14       A       93       93       83     40
29    30       Livia    Male   13       C       95       65       25     91
35    36  Anna-diane  Female   15       C       93       53       10     29
39    40      Luelle    Male   13       B      100       52       89     76
49    50      Karrie    Male   14       A       94       15       66     34
70    71         Bil  Female   15       C       95       32       91     48
134  135     Humfrid  Female   13       B       96      100       42     62
147  148       Danni  Female   13       B       92       67       13     25
150  151      Herold    Male   13       A       92       97       62     69
161  162        Pepi  Female   13       A      100       64       16     20
163  164       Alard  Female   13       A       91       12       15     70
168  169      Ilaire    Male   14       C       95       56        4    100
173  174     Margaux    Male   14       A       94       28        6      9
175  176        Ivan    Male   14       C       95       21       51     33
176  177      Guntar    Male   13       B       92       36       59     48
178  179         Val    Male   13       B       95       73       91     61
180  181     Davidde    Male   13       C       98      100       23     84
195  196        Nita    Male   14       A       92       57       31     75
197  198       Carol  Female   14       B       98       13       35      4
222  223        Leda  Female   15       B       92       76       72     71
223  224       Tabbi  Female   13       A      100       95       36     10
233  234    Mortimer    Male   15       C       91       33       71     81
235  236       Nadia  Female   15       B       98       30       37     56
236  237       Britt    Male   15       C       92       87       38     53
243  244     Domingo    Male   13       C       95       63       65     71
247  248        Kaia    Male   15       B       93       48       82     44

In [68]:
print(df["Maths"].mean())

53.016

In [70]:
print(df["Science"].max())

100

In [71]:
print(df["English"].min())

1

In [78]:
print(df[["Maths","English","Science"]].mean())

Maths      53.016
English    47.980
Science    51.440
dtype: float64

In [80]:
print(df[["Maths","English"]].max())

Maths      100
English    100
dtype: int64

In [81]:
df.groupby("Gender")["Maths"].mean()

Gender
Female    50.364407
Male      55.386364
Name: Maths, dtype: float64

In [85]:
df.groupby("Section")["Science"].max()

Section
A    100
B    100
C    100
Name: Science, dtype: int64

In [90]:
df.sort_values(by="Maths")

      id     Name  Gender  Age Section  Science  English  History  Maths
225  226    Blake  Female   15       B       16        4       49      1
130  131   Blisse  Female   15       B       85       30       50      2
19    20   Ashlan    Male   13       B       41        6       17      3
136  137   Ailene  Female   15       C       52       39       37      3
139  140    Ricky  Female   13       B       21       65       90      4
..   ...      ...     ...  ...     ...      ...      ...      ...    ...
61    62    Fanny  Female   13       C       49       90       13     98
123  124     Orin  Female   15       B       70       75       21     99
87    88  Sheffie  Female   15       C       44       55       51    100
76    77    David  Female   13       B       27        2       63    100
168  169   Ilaire    Male   14       C       95       56        4    100

[250 rows x 9 columns]

In [91]:
df.sort_values(by="Maths",ascending=False)

      id     Name  Gender  Age Section  Science  English  History  Maths
76    77    David  Female   13       B       27        2       63    100
87    88  Sheffie  Female   15       C       44       55       51    100
168  169   Ilaire    Male   14       C       95       56        4    100
123  124     Orin  Female   15       B       70       75       21     99
61    62    Fanny  Female   13       C       49       90       13     98
..   ...      ...     ...  ...     ...      ...      ...      ...    ...
139  140    Ricky  Female   13       B       21       65       90      4
19    20   Ashlan    Male   13       B       41        6       17      3
136  137   Ailene  Female   15       C       52       39       37      3
130  131   Blisse  Female   15       B       85       30       50      2
225  226    Blake  Female   15       B       16        4       49      1

[250 rows x 9 columns]

In [92]:
df.sort_values(by="English")

      id      Name  Gender  Age Section  Science  English  History  Maths
57    58     Issie    Male   14       A       64        1       74      6
42    43   Brandie    Male   15       B       43        2       17     78
90    91      Linn    Male   13       C       23        2       42     43
76    77     David  Female   13       B       27        2       63    100
185  186    Alaine    Male   15       A       48        2       63     91
..   ...       ...     ...  ...     ...      ...      ...      ...    ...
51    52    Rollie  Female   13       A       17       99       29     85
155  156     Sarah  Female   13       B       55       99        8     72
122  123  Brandise    Male   13       A       18      100       39      8
180  181   Davidde    Male   13       C       98      100       23     84
134  135   Humfrid  Female   13       B       96      100       42     62

[250 rows x 9 columns]

In [93]:
df.sort_values("Maths",ascending=False).head(5)

      id     Name  Gender  Age Section  Science  English  History  Maths
76    77    David  Female   13       B       27        2       63    100
87    88  Sheffie  Female   15       C       44       55       51    100
168  169   Ilaire    Male   14       C       95       56        4    100
123  124     Orin  Female   15       B       70       75       21     99
61    62    Fanny  Female   13       C       49       90       13     98

In [94]:
df["Science"].tail(5)

245    28
246     1
247    93
248    35
249    50
Name: Science, dtype: int64

In [97]:
df["total"]=df["Science"]+df["Maths"]+df["English"]+df["History"]
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,total
0,1,Bronnie,Female,13,C,21,81,62,49,213
1,2,Lemmie,Male,15,B,29,41,17,40,127
2,3,Danya,Female,14,C,12,87,16,96,211
3,4,Denna,Female,14,B,15,53,82,33,183
4,5,Jocelin,Male,14,A,43,6,3,21,73
...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78
246,247,Rog,Female,13,B,1,4,68,65,138
247,248,Kaia,Male,15,B,93,48,82,44,267
248,249,Anni,Female,14,B,35,73,66,59,233
249,250,Fernande,Male,15,B,50,8,80,78,216

In [99]:
print(df["total"].max())

361

In [114]:
df.sort_values("total",ascending=False).head(1)

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25

In [103]:
df["Avg"]=df["total"]/4

In [106]:
df

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
0,1,Bronnie,Female,13,C,21,81,62,49,213,53.25
1,2,Lemmie,Male,15,B,29,41,17,40,127,31.75
2,3,Danya,Female,14,C,12,87,16,96,211,52.75
3,4,Denna,Female,14,B,15,53,82,33,183,45.75
4,5,Jocelin,Male,14,A,43,6,3,21,73,18.25
...,...,...,...,...,...,...,...,...,...,...,...
245,246,Nickie,Male,13,C,28,15,25,10,78,19.50
246,247,Rog,Female,13,B,1,4,68,65,138,34.50
247,248,Kaia,Male,15,B,93,48,82,44,267,66.75
248,249,Anni,Female,14,B,35,73,66,59,233,58.25
249,250,Fernande,Male,15,B,50,8,80,78,216,54.00

In [120]:
df[df["total"]>300]

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
5,6,Malissa,Female,14,C,98,51,85,76,310,77.50
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25
23,24,Valma,Female,14,C,48,83,79,95,305,76.25
26,27,Charmine,Female,14,A,93,93,83,40,309,77.25
39,40,Luelle,Male,13,B,100,52,89,76,317,79.25
68,69,Nil,Female,15,A,84,97,70,96,347,86.75
91,92,Daffi,Female,15,A,79,82,99,81,341,85.25
120,121,Patrizia,Male,13,A,79,88,96,93,356,89.00
149,150,Inger,Female,13,B,53,95,75,81,304,76.00
150,151,Herold,Male,13,A,92,97,62,69,320,80.00
178,179,Val,Male,13,B,95,73,91,61,320,80.00
180,181,Davidde,Male,13,C,98,100,23,84,305,76.25
200,201,Ruddie,Female,15,B,84,97,88,64,333,83.25
222,223,Leda,Female,15,B,92,76,72,71,311,77.75

In [124]:
df[df["Age"]>75]

Empty DataFrame
Columns: [id, Name, Gender, Age, Section, Science, English, History, Maths, total, Avg]
Index: []

In [133]:
df.groupby("Section")["total"].max()

Section
A    356
B    333
C    361
Name: total, dtype: int64

In [139]:
df.loc[df.groupby("Section")["total"].idxmax()]

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
120,121,Patrizia,Male,13,A,79,88,96,93,356,89.00
200,201,Ruddie,Female,15,B,84,97,88,64,333,83.25
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25

In [171]:
a=df[(df["Gender"]=="Female")]
a

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
0,1,Bronnie,Female,13,C,21,81,62,49,213,53.25
2,3,Danya,Female,14,C,12,87,16,96,211,52.75
3,4,Denna,Female,14,B,15,53,82,33,183,45.75
5,6,Malissa,Female,14,C,98,51,85,76,310,77.50
6,7,Ichabod,Female,14,B,38,74,54,60,226,56.50
...,...,...,...,...,...,...,...,...,...,...,...
238,239,Ashlin,Female,14,A,49,47,19,55,170,42.50
242,243,Morrie,Female,13,B,17,24,41,21,103,25.75
244,245,Jesselyn,Female,15,C,11,53,15,13,92,23.00
246,247,Rog,Female,13,B,1,4,68,65,138,34.50
248,249,Anni,Female,14,B,35,73,66,59,233,58.25

In [176]:
a.loc[a["total"].idxmax()]

id             69
Name          Nil
Gender     Female
Age            15
Section         A
Science        84
English        97
History        70
Maths          96
total         347
Avg         86.75
Name: 68, dtype: object

In [177]:
mal=df[df["Gender"]=="Male"]
mal

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
1,2,Lemmie,Male,15,B,29,41,17,40,127,31.75
4,5,Jocelin,Male,14,A,43,6,3,21,73,18.25
7,8,Beverlie,Male,14,B,25,51,41,80,197,49.25
8,9,Corrine,Male,15,A,39,16,22,49,126,31.50
9,10,Tate,Male,15,C,35,25,37,27,124,31.00
...,...,...,...,...,...,...,...,...,...,...,...
241,242,Janey,Male,15,C,3,49,67,96,215,53.75
243,244,Domingo,Male,13,C,95,63,65,71,294,73.50
245,246,Nickie,Male,13,C,28,15,25,10,78,19.50
247,248,Kaia,Male,15,B,93,48,82,44,267,66.75
249,250,Fernande,Male,15,B,50,8,80,78,216,54.00

In [180]:
mal.loc[mal["total"].idxmax()]

id            11
Name        Dunn
Gender      Male
Age           15
Section        C
Science      100
English       93
History       87
Maths         81
total        361
Avg        90.25
Name: 10, dtype: object

In [187]:
df.loc[df.groupby("Section")["Avg"].idxmax()]

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
120,121,Patrizia,Male,13,A,79,88,96,93,356,89.00
200,201,Ruddie,Female,15,B,84,97,88,64,333,83.25
10,11,Dunn,Male,15,C,100,93,87,81,361,90.25

In [188]:
df[df["Maths"]>35]

,id,Name,Gender,Age,Section,Science,English,History,Maths,total,Avg
0,1,Bronnie,Female,13,C,21,81,62,49,213,53.25
1,2,Lemmie,Male,15,B,29,41,17,40,127,31.75
2,3,Danya,Female,14,C,12,87,16,96,211,52.75
5,6,Malissa,Female,14,C,98,51,85,76,310,77.50
6,7,Ichabod,Female,14,B,38,74,54,60,226,56.50
...,...,...,...,...,...,...,...,...,...,...,...
243,244,Domingo,Male,13,C,95,63,65,71,294,73.50
246,247,Rog,Female,13,B,1,4,68,65,138,34.50
247,248,Kaia,Male,15,B,93,48,82,44,267,66.75
248,249,Anni,Female,14,B,35,73,66,59,233,58.25
249,250,Fernande,Male,15,B,50,8,80,78,216,54.00

In [203]:
# which gender has the higher avg marks in science
df.groupby("Gender")["Science"].mean().idxmax()

'Male'